title: Dance of Death
description: The Dance of Death (de. ‘Totentanz’, fr. ‘Danse macabre’, uk. ‘Танок Смерті’, ru. ‘Пляска Смерти’) is a genre of allegory in the medieval European art represeting the equalizing power of death. Our website lists the popular set of Danse Macabre episodes in German, French, English, Ukrainian and Russian languages.
baseurl: "totentanz"
url: "https://catskald.github.io"
github_username: CatSkald
theme: jekyll-theme-midnight
