title: Dance of Death
description: >-
  Danse macabre, Totentanz, Пляска Смерти
  The Danse Macabre is a genre of allegory in the European art of the Late Middle Ages
baseurl: "totentanz"
url: "https://catskald.github.io"
github_username:  CatSkald
theme: jekyll-theme-midnight
