title: Dance of Death
description: >-
  Totentanz ⨳ Danse macabre ⨳ Танок Смерті ⨳ Пляска Смерти

  The Danse Macabre is a genre of allegory in the European art of the Late Middle Ages. The texts on this website are represented in the following languages (in the same order): German, French, English, Ukrainian, Russian.
baseurl: "totentanz"
url: "https://catskald.github.io"
github_username: CatSkald
theme: jekyll-theme-midnight
